### ISSUE TITLE
please create strong name!

### ISSUE THREAD

**Issue by bitministry** [nhibernate/fluent-nhibernate#426] opened 2019-01-27 21:08 UTC
I need a **strong named product**, that is using FluentNHibernate, so it has to be strongly named. 
**There is no other way, .net compiler does not bind assembly without a strong name!**

Let me list the benefits of strong naming your assembly first:
1. Strong naming your assembly allows you to include your assembly into the Global Assembly Cache (GAC). Thus it allows you to share it among multiple applications.
2. Strong naming guarantees a unique name for that assembly. Thus no one else can use the same assembly name.
3. Strong name protect the version lineage of an assembly. A strong name can ensure that no one is able to produce a subsequent version of your assembly. Application users are ensured that a version of the assembly they are loading come from the same publisher that created the version the application was built with.
4. Strong named assemblies are signed with a digital signature. This protects the assembly from modification. Any tampering causes the verification process that occurs at assembly load time to fail. An exception is generated and the assembly is not loaded.

More on strong naming from Microsoft is in Strong-Named Assemblies (MSDN).
https://docs.microsoft.com/en-us/dotnet/framework/app-domains/strong-named-assemblies

----
for now I just hacked a strong named into your code, but its detached from your source :(

**Comment by hazzik** [comment] 2020-09-18 07:50
Duplicate of #450

**Closed by hazzik** 2020-09-18 07:50 UTC
