### ISSUE TITLE
Error while mapping proxies for Entities in net9.0

### ISSUE THREAD

**Issue by sukreshmanda** [nhibernate/fluent-nhibernate#716] opened 2024-11-06 13:44 UTC
## Code Used

```c-sharp
public class Employee
    {
        public virtual string Name { get; set; }
        public virtual long Id { get; set; }
    }

    public class EmployeeMap : ClassMap<Employee>
    {
        public EmployeeMap()
        {
            Table("employee");
            Id(e => e.Id).CustomSqlType("Serial").GeneratedBy.Native();
            Map(e => e.Name).Column("name");
        }
    }
```

Error:
```
NHibernate.InvalidProxyTypeException: The following types may not be used as proxies:
TodoAPI.Models.Employee: method MemberwiseClone should be 'public/protected virtual' or 'protected internal virtual'
   at NHibernate.Cfg.Configuration.ValidateEntities()
   at NHibernate.Cfg.Configuration.Validate()
   at NHibernate.Cfg.Configuration.BuildSessionFactory()
   at FluentNHibernate.Cfg.FluentConfiguration.BuildSessionFactory()
```

**Comment by hazzik** [comment] 2024-11-07 23:45
Update NHibernate to 5.5.2

This is a duplicate of https://github.com/nhibernate/nhibernate-core/issues/3536

**Closed by hazzik** 2024-11-07 23:45 UTC
