### ISSUE TITLE
Property convention does not apply precision

### ISSUE THREAD

**Issue by kriewall** [nhibernate/fluent-nhibernate#527] opened 2022-02-19 01:04 UTC
### What is the current bug behavior?

I have defined the following property convention with the intent of limiting the precision of all double values to 15 as written to an Oracle dB:

```
    public class PrecisionConvention : IPropertyConvention
    {
        public void Apply(IPropertyInstance instance)
        {
            if (instance.Type == typeof(double)) instance.Precision(15);
        }
    }
```

I have a value with exceedingly high precision for a `Percentage` class being written to the dB.  I can see that the precision is being updated for my `Percentage` class by `PrecisionConvention`; however, when the value is written to the dB, it is done so at its unmodified precision.

![image](https://user-images.githubusercontent.com/38048622/154779354-c4a51d56-baf9-4e28-92ca-9cec07eb91ee.png)
![image](https://user-images.githubusercontent.com/38048622/154779386-96ec1cc8-72bf-4875-bd11-7de3c6c8ee2e.png)

### What is the expected correct behavior?

Setting the precision via an implementation of `IPropertyConvention` should be reflected in the database. 

![image](https://user-images.githubusercontent.com/38048622/154779447-c8fc4270-0ad2-4e1a-be8f-9844ddf13d54.png)

### Impact
The inability to limit the precision when writing to the dB is causing the Oracle client to bomb out - there's a known issue with Oracle where doubles may be written to the dB in higher precision than can be represented by C# (I reported this issue long ago to them but still have yet to see a fix), so I need a way to limit the precision for all doubles before write.  I'd like to request either a fix or a recommendation for a workaround.

**Comment by hazzik** [comment] 2022-10-12 21:50
Schema update does not currently update the precision of columns if the [base] type is the same. So, this is a 
Duplicate of https://github.com/nhibernate/nhibernate-core/issues/1895#issuecomment-436062352

**Comment by hazzik** [comment] 2022-10-12 21:50
Duplicate of https://github.com/nhibernate/nhibernate-core/issues/1895

**Closed by hazzik** 2022-10-12 21:50 UTC
