### ISSUE TITLE
HasMany() with latest NHibernate 5.3 not eagar loading. Not generating left outer joins.

### ISSUE THREAD

**Issue by svkrishnareddy** [nhibernate/fluent-nhibernate#482] opened 2020-12-17 01:50 UTC
We upgraded on to NHibernate 5.3.5 from 3 and FluentNhibernate to 3.1

```csharp
  public class ReasonDataAccessorAssignment
  {
    public virtual int Id { get; protected internal set; }
    public virtual Reason Reason{ get; protected internal set; }
 }

public class Reason
  {
    public virtual int ID { get; protected internal set; }
    public virtual IList<ReasonDataAccessorAssignment> ReasonDataAccessorAssignments { get; protected internal set; }
  }
```

Class map:
```csharp
public class ReasonMap : ClassMap<Reason>
  {
    public ReasonMap()
    {
      var tableMeta = "Reason";
      this.Table(tableMeta);

      Id(x => x.ID).Column("Reason_id").GeneratedBy.Identity();

      HasMany(x => x.ReasonDataAccessorAssignments)
        .KeyColumn("Reason_id")
        .Cascade.AllDeleteOrphan()
        .Not.LazyLoad()
        .BatchSize(100);
    }
}
```

Repository call:
```csharp
var reasons = (from s in _session.Query<Reason>()
              where s.ReasonDataAccessorAssignments != null
              select s).ToList();
```
This query is NOT generating ReasonDataAccessorAssignment table as LEFT OUTER JOIN with latest version
Previous version NHibernate 3 is generating LEFT OUTER JOIN with above query

**Comment by hazzik** [comment] 2020-12-17 02:17
Duplicate of https://github.com/nhibernate/nhibernate-core/issues/2639

**Closed by hazzik** 2020-12-17 02:17 UTC
