### ISSUE TITLE
OneToManyPart's Where method uses property name instead of column name from ClassMap

### ISSUE THREAD

**Issue by wilsonhut** [nhibernate/fluent-nhibernate#183] opened 2012-10-18 13:56 UTC
- In the ClassMap<Order>...

Map(o => o.IsDeleted, "deleteFlag");
- In the ClassMap<Customer>...

HasMany(c => c.Orders).Where(c => c.IsDeleted == false);

 ... results in "Invalid column name 'IsDeleted'"
- If I change the PROPERTY name from "IsDeleted" to "DeleteFlag", it doesn't fail. Shouldn't the Where go to the ClassMap<Order> for that property to get the column name from the mapping instead of using reflection to get the property name?

**Comment by hazzik** [comment] 2020-09-18 09:40
Duplicate of #107

**Closed by hazzik** 2020-09-18 09:40 UTC
