### ISSUE TITLE
Possible to get support for Fluent mapping class constructors with parameters?

### ISSUE THREAD

**Issue by iiian** [nhibernate/fluent-nhibernate#384] opened 2018-01-05 05:43 UTC
For instance, I'd like to be able to create some class:

```
public class MyClassMap : ClassMap<MyType>
{
   public MyClassMap(object argumentOne, object argumentTwo)
   {
      // leverage arguments to further customize creation of fluent mapping.
   }
}
```

Understand if this is an unachievable design constraint.

This is an issue because I have an issue with not being able to do this.

**Comment by hazzik** [comment] 2022-10-06 04:17
Duplicate of #375

**Closed by hazzik** 2022-10-06 04:17 UTC
